// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TellMe.iOS
{
	public partial class EventViewController : UITableViewController
	{
		public EventViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
